default_language_version:
  python: python3.12
repos:
- repo: https://github.com/PyCQA/bandit
  rev: '1.8.2'
  hooks:
    - id: bandit
      args: ['-r', '.']
#      additional_dependencies: ['six:1.17.0', ]