services:
  resilmesh_ap_silentpush:
    hostname: "silentpush-enrichment"
    restart: unless-stopped
    env_file:
      - "../resilmesh.conf"
    build:
      context: "./"
    healthcheck:
      test: "(ps aux | grep -i subscriber.py | grep -v grep)"
      interval: 1s
      retries: 60
    deploy:
      replicas: 2
    networks:
      - resilmesh_network
    depends_on: ["resilmesh_ap_nats"]
    volumes:
      - ./sp-enrichment:/home/app/sp-enrichment