name: Bandit
on: push

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          bandit -c bandit.yaml -iii -r .
